### ISSUE TITLE
compile issue - new, clean system

### ISSUE THREAD

**Issue by morpheusbeing** [sehraf/Lua4RS#5]
Have just rebuilt computer Debian Stretch , installed Lua 5.3, and now get the following error when compiling:

   make -j2
   g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DQT_WEBKIT -DRS_ENABLE_GXS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../libretroshare/src -I../../retroshare-gui/src -I. -I. -o Lua4RSPlugin.o Lua4RSPlugin.cpp
   g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DQT_WEBKIT -DRS_ENABLE_GXS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../libretroshare/src -I../../retroshare-gui/src -I. -I. -o Lua4RSNotify.o Lua4RSNotify.cpp
   In file included from Lua4RSNotify.cpp:6:0:
   Lua/LuaCore.h:15:17: fatal error: lua.h: No such file or directory
   compilation terminated.
   Makefile:394: recipe for target 'Lua4RSNotify.o' failed
   make: *** [Lua4RSNotify.o] Error 1
   make: *** Waiting for unfinished jobs....
   In file included from Lua4RSPlugin.cpp:16:0:
   Lua/LuaCore.h:15:17: fatal error: lua.h: No such file or directory
   compilation terminated.
   Makefile:351: recipe for target 'Lua4RSPlugin.o' failed
   make: *** [Lua4RSPlugin.o] Error 1

**Comment by sehraf** [comment]
please try the latest version 643b1e2e3ae07bff0c298a97dff925df1e285184 and report back if it works for you or not

**Comment by morpheusbeing** [comment]
I have uninstalled/installed Debian Stretch Lua 5.3 package via Synaptic. I now get the following:

      ~/rs06/plugins/Lua4RS$ qmake
       Project ERROR: Package lua not found

**Comment by sehraf** [comment]
try the latest version please
